#!/bin/bash

set -eEuo pipefail
set -x

DOCKER_REPO=tessereth/test-summary-buildkite-plugin

on_failure() {
    echo "Command failed with exit status: $?"
    if [[ "$BUILDKITE_PLUGIN_TEST_SUMMARY_FAIL_ON_ERROR" != "true" ]]; then
        echo "Suppressing failure so pipeline can continue (if you do not want this behaviour, set fail_on_error to true)"
        exit 0
    fi
}

trap on_failure ERR

# cd to plugin directory
cd "$( dirname "${BASH_SOURCE[0]}" )/.."
TAG=$(git describe --tags --exact-match 2> /dev/null || true)

if [[ -n "$TAG" ]]; then
    echo "Found tag $TAG, pulling from docker hub"
    IMAGE="$DOCKER_REPO:$TAG"
    docker pull "$IMAGE"
else
    echo "No tag found, building image locally"
    IMAGE=test-summary:$BUILDKITE_JOB_ID
    docker build -t "$IMAGE" .
fi

echo "Running container"

BUILDKITE_AGENT_PATH="$(which buildkite-agent)"
echo "$BUILDKITE_AGENT_PATH"
ls -la "$BUILDKITE_AGENT_PATH"

docker run --rm \
  --mount type=bind,src="$BUILDKITE_AGENT_PATH",dst=/usr/bin/buildkite-agent \
  -e BUILDKITE_BUILD_ID -e BUILDKITE_JOB_ID -e BUILDKITE_AGENT_ACCESS_TOKEN -e BUILDKITE_PLUGINS \
  "$IMAGE"
